/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.projetopi.hakuzanloja.view;

import com.projetopi.hakuzanloja.controller.ProdutoDao;
import com.projetopi.hakuzanloja.model.ProdutosAtual;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author snubd
 */
public class ListaProdutos extends javax.swing.JInternalFrame {
     
    /**
     * Creates new form ListaProdutos
     */
    public ListaProdutos() {
        initComponents();
        
        addLinhaJtable();
    }
    
     private void addLinhaJtable(){
        
        DefaultTableModel model = (DefaultTableModel) tableProdutos.getModel();
        
        Object linhaData[] = new Object[3];
        
        for(int i= 0; i< ProdutosAtual.getListaProd().size();i++){
            linhaData[0] = ProdutosAtual.getListaProd().get(i).getProduto();
            linhaData[1] = ProdutosAtual.getListaProd().get(i).getDescricao();
            linhaData[2] = ProdutosAtual.getListaProd().get(i).getValor();
            model.addRow(linhaData);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableProdutos = new javax.swing.JTable();

        tableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Desc", "Preço"
            }
        ));
        jScrollPane2.setViewportView(tableProdutos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableProdutos;
    // End of variables declaration//GEN-END:variables
}
