CREATE DATABASE LOJA_GEEK; 
USE LOJA_GEEK;

CREATE TABLE TB_NIVEL(
	PK_ID INT NOT NULL AUTO_INCREMENT,
	DS_NOME VARCHAR(30) NOT NULL,
    PRIMARY KEY(PK_ID)
);

INSERT INTO TB_NIVEL (DS_NOME)
VALUES ('Nível 1');

CREATE TABLE TB_USUARIO(
	PK_ID INT NOT NULL AUTO_INCREMENT,
	DS_LOGIN VARCHAR(50) NOT NULL,
    DS_SENHA VARCHAR(20) NOT NULL,
    NR_TELEFONE VARCHAR(20),
    DS_CEP VARCHAR(10) NOT NULL,
    DS_UF VARCHAR(2),
    DS_CIDADE VARCHAR(60) NOT NULL,
    DS_BAIRRO VARCHAR(60) NOT NULL,
    DS_LOGRADOURO VARCHAR(60) NOT NULL,
    NR_LOGRADOURO VARCHAR(20) NOT NULL,
    DS_NOME VARCHAR(80) NOT NULL,
    DS_EMAIL VARCHAR(80),
    NR_CPFCNPJ VARCHAR(20),
    FK_NIVEL INT NOT NULL,
    PRIMARY KEY(PK_ID),
    FOREIGN KEY (FK_NIVEL) REFERENCES TB_USUARIO(PK_ID)
);

INSERT INTO TB_USUARIO (DS_LOGIN, DS_SENHA, NR_TELEFONE, DS_CEP, DS_UF, DS_CIDADE, DS_BAIRRO, DS_LOGRADOURO, NR_LOGRADOURO, DS_NOME, DS_EMAIL, NR_CPFCNPJ, FK_NIVEL) 
VALUES ('admin', '123', '1234567890', '12345-678', 'SP', 'São Paulo', 'Bairro', 'Rua Teste', '123', 'Administrador', 'admin@example.com', '12345678900', 1);

CREATE TABLE `TB_FORMAPAGAMENTO` (
  `PK_ID` int NOT NULL AUTO_INCREMENT,
  `FK_USUARIO` int DEFAULT NULL,
  `DS_CARTAO` varchar(50) DEFAULT NULL,
  `DS_TIPO` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`PK_ID`),
  KEY `FK_USUARIO` (`FK_USUARIO`),
  CONSTRAINT `TB_FORMAPAGAMENTO_ibfk_1` FOREIGN KEY (`FK_USUARIO`) REFERENCES `TB_USUARIO` (`PK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE TB_CATEGORIA(
	PK_ID INT NOT NULL AUTO_INCREMENT,
    DS_TIPO VARCHAR(30) NOT NULL,
    PRIMARY KEY(PK_ID)
);

CREATE TABLE TB_PRODUTO(
	PK_ID INT NOT NULL AUTO_INCREMENT,
    DS_NOME VARCHAR(70) NOT NULL,
    DS_DESCRICAO VARCHAR(255),
    VL_COMPRA NUMERIC(14,2),
    VL_VENDA NUMERIC(14,2),
    FK_CATEGORIA INT, 
    PRIMARY KEY(PK_ID),
    FOREIGN KEY(FK_CATEGORIA) REFERENCES TB_CATEGORIA(PK_ID)
);

INSERT INTO TB_CATEGORIA (DS_TIPO)
VALUES ('CALÇA');

INSERT INTO TB_CATEGORIA (DS_TIPO)
VALUES ('BLUSA');

INSERT INTO TB_PRODUTO (DS_NOME, DS_DESCRICAO, VL_COMPRA, VL_VENDA, FK_CATEGORIA) 
VALUES ('Produto 1', 'Descrição do Produto 1', 50.00, 75.00, 1);

-- Inserção do Produto 2
INSERT INTO TB_PRODUTO (DS_NOME, DS_DESCRICAO, VL_COMPRA, VL_VENDA, FK_CATEGORIA) 
VALUES ('Produto 2', 'Descrição do Produto 2', 40.00, 60.00, 1);

-- Inserção do Produto 3
INSERT INTO TB_PRODUTO (DS_NOME, DS_DESCRICAO, VL_COMPRA, VL_VENDA, FK_CATEGORIA) 
VALUES ('Produto 3', 'Descrição do Produto 3', 30.00, 45.00, 2);

-- Inserção do Produto 4
INSERT INTO TB_PRODUTO (DS_NOME, DS_DESCRICAO, VL_COMPRA, VL_VENDA, FK_CATEGORIA) 
VALUES ('Produto 4', 'Descrição do Produto 4', 55.00, 85.00, 2);

CREATE TABLE `TB_PEDIDO` (
  `PK_ID` int NOT NULL AUTO_INCREMENT,
  `VL_TOTAL` decimal(14,2) DEFAULT NULL,
  `DT_PEDIDO` date DEFAULT NULL,
  `TG_STATUS` varchar(1) DEFAULT NULL,
  `FK_USUARIO` int DEFAULT NULL,
  `FK_FORMAPAGAMENTO` int DEFAULT NULL,
  PRIMARY KEY (`PK_ID`),
  KEY `FK_USUARIO` (`FK_USUARIO`),
  KEY `FK_TB_PEDIDO_TB_FORMAPAGAMENTO` (`FK_FORMAPAGAMENTO`),
  CONSTRAINT `FK_TB_PEDIDO_TB_FORMAPAGAMENTO` FOREIGN KEY (`FK_FORMAPAGAMENTO`) REFERENCES `TB_FORMAPAGAMENTO` (`PK_ID`),
  CONSTRAINT `TB_PEDIDO_ibfk_1` FOREIGN KEY (`FK_USUARIO`) REFERENCES `TB_USUARIO` (`PK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

CREATE TABLE TB_ITENSPEDIDO(
	PK_ID INT NOT NULL AUTO_INCREMENT,
    FK_PRODUTO INT NOT NULL,
    QT_PRODUTO INT NOT NULL,
    VL_UNITARIO NUMERIC(14,2) NOT NULL,
    VL_TOTAL NUMERIC(14,2) NOT NULL,
    FK_PEDIDO INT NOT NULL,
    PRIMARY KEY(PK_ID),
    FOREIGN KEY(FK_PEDIDO) REFERENCES TB_PEDIDO(PK_ID)
);


