CREATE DATABASE LOJA_GEEK;

/*CRUD DA TELA DE NÍVEIS*/

/*PESQUISA DE TODOS OS ITENS*/
SELECT  
	PK_ID,
    DS_NOME
FROM TB_NIVEL;

/*SELECT ITEM SELCIONADO*/
SELECT  
	PK_ID,
    DS_NOME
FROM TB_NIVEL 
WHERE PK_ID = 1;
 
/*INSERT DA INFORMAÇÃO*/
INSERT INTO TB_NIVEL (DS_NOME)
VALUES ('Nível 1');

/*UPDATE DA INFORMAÇÃO*/
UPDATE TB_NIVEL
SET DS_NOME = 'VENDEDOR'
WHERE PK_ID = 1;

/*DELETE DA INFORMAÇÃO*/
DELETE FROM TB_NIVEL
WHERE PK_ID = 1;

/*------------------------------------*/

/*CRUDE DA TELA CATEGORIAS*/
    
/*PESQUISA DE TODOS OS ITENS*/
SELECT  
	PK_ID,
    DS_TIPO
FROM TB_CATEGORIA;

/*SELECT ITEM SELCIONADO*/
SELECT  
	PK_ID,
    DS_TIPO
FROM TB_CATEGORIA
WHERE PK_ID = 1;

/*INSERT DA INFORMAÇÃO*/
INSERT INTO TB_CATEGORIA (DS_TIPO)
VALUES ('Categoria A');


/*UPDATE DA INFORMAÇÃO*/
UPDATE TB_CATEGORIA
SET DS_TIPO = 'Novo Tipo da Categoria'
WHERE PK_ID = 1;

/*DELETE DA INFORMAÇÃO*/
DELETE FROM TB_CATEGORIA
WHERE PK_ID = 1;

/*------------------------------------*/

/*CRUDE DA TELA PRODUTO*/

/*PESQUISA DE TODOS OS ITENS*/
SELECT  
	PRO.PK_ID,
    PRO.DS_NOME,
    PRO.DS_DESCRICAO,
    PRO.VL_COMPRA,
    PRO.VL_VENDA,
    PRO.FK_CATEGORIA,
    CAT.PK_ID,
    CAT.DS_TIPO
FROM TB_PRODUTO AS PRO
LEFT JOIN TB_CATEGORIA AS CAT ON CAT.PK_ID = PRO.FK_CATEGORIA;

/*SELECT ITEM SELCIONADO*/
	
SELECT
    PK_ID,
    DS_NOME,
    DS_DESCRICAO,
    VL_COMPRA,
    VL_VENDA
FROM TB_PEDIDO
WHERE PK_ID = 1;

/*INSERT DA INFORMAÇÃO*/
INSERT INTO TB_PRODUTO (DS_NOME, DS_DESCRICAO, VL_COMPRA, VL_VENDA, FK_CATEGORIA)
VALUES ('Produto 1', 'Descrição do Produto 1', 80.00, 120.00, 1);

/*UPDATE DA INFORMAÇÃO*/
UPDATE TB_PRODUTO
SET DS_NOME = 'Novo Nome do Produto',
    DS_DESCRICAO = 'Nova Descrição',
    VL_COMPRA = 120.00,
    VL_VENDA = 180.00
WHERE PK_ID = 1;

/*DELETE DA INFORMAÇÃO*/
DELETE FROM TB_PRODUTO
WHERE PK_ID = 1;

/*------------------------------------*/

/*CRUDE DA TELA PEDIDO*/
CREATE TABLE TB_PEDIDO(
	PK_ID INT NOT NULL AUTO_INCREMENT,
    VL_TOTAL DECIMAL(14,2),
    DT_PEDIDO DATE,
    TG_STATUS VARCHAR(1),
    FK_USUARIO INT,
    PRIMARY KEY(PK_ID)
);
/*PESQUISA DE TODOS OS ITENS*/

SELECT  
	 PK_ID,
     VL_TOTAL,
     DT_PEDIDO,
     TG_STATUS,
     FK_USUARIO
FROM TB_PEDIDO;

/*SELECT ITEM SELCIONADO*/
SELECT  
	 PK_ID,
     VL_TOTAL,
     DT_PEDIDO,
     TG_STATUS,
     FK_USUARIO
FROM TB_PEDIDO 
WHERE PK_ID = 1;

/*INSERT DA INFORMAÇÃO*/
INSERT INTO TB_PEDIDO (VL_TOTAL, DT_PEDIDO, TG_STATUS, FK_USUARIO)
VALUES (100.00, '2023-09-23', 'P', 1);

/*UPDATE DA INFORMAÇÃO*/
UPDATE TB_PEDIDO
SET VL_TOTAL = 150.00,
    DT_PEDIDO = '2023-09-24',
    TG_STATUS = 'A'
WHERE PK_ID = 1;

/*DELETE DA INFORMAÇÃO*/
DELETE FROM TB_PEDIDO
WHERE PK_ID = 1;

/*------------------------------------*/


/*CRUDE TELA DE ITENS PEDIDO*/
/*PESQUISA DE TODOS OS ITENS*/

SELECT
	PK_ID,
    FK_PRODUTO,
    QT_PRODUTO,
    VL_UNITARIO,
    VL_TOTAL,
    FK_PEDIDO
FROM TB_ITENSPEDIDO;

/*SELECT ITEM SELCIONADO*/

SELECT 
	PK_ID,
    FK_PRODUTO,
    QT_PRODUTO,
    VL_UNITARIO,
    VL_TOTAL,
    FK_PEDIDO
FROM TB_ITENSPEDIDO;
WHERE PK_ID = 1;

/*INSERT DA INFORMAÇÃO*/

INSERT INTO TB_ITENSPEDIDO (FK_PRODUTO, QT_PRODUTO, VL_UNITARIO, VL_TOTAL, FK_PEDIDO)
VALUES (1, 5, 10.00, 50.00, 1);

/*UPDATE DA INFORMAÇÃO*/

UPDATE TB_ITENSPEDIDO
SET FK_PRODUTO = 2,
    QT_PRODUTO = 15,
    VL_UNITARIO = 25.00,
    VL_TOTAL = 375.00,
    FK_PEDIDO = 2
WHERE PK_ID = 1;

/*DELETE DA INFORMAÇÃO*/

DELETE FROM TB_ITENSPEDIDO
WHERE PK_ID = 1;

/*------------------------------------*/


/*CRUDE TELA DE USUARIO*/

/*PESQUISA DE TODOS OS ITENS*/

SELECT
	PK_ID,
    DS_LOGIN,
    DS_SENHA,
    NR_TELEFONE,
    DS_CEP,
    DS_UF,
    DS_CIDADE,
    DS_BAIRRO,
    DS_LOGRADOURO,
    NR_LOGRADOURO,
    DS_NOME,
    DS_EMAIL,
    NR_CPFCNPJ,
    FK_NIVEL
FROM TB_USUARIO;

/*SELECT ITEM SELCIONADO*/

SELECT
	PK_ID,
    DS_LOGIN,
    DS_SENHA,
    NR_TELEFONE,
    DS_CEP,
    DS_UF,
    DS_CIDADE,
    DS_BAIRRO,
    DS_LOGRADOURO,
    NR_LOGRADOURO,
    DS_NOME,
    DS_EMAIL,
    NR_CPFCNPJ,
    FK_NIVEL
FROM TB_USUARIO;
WHERE PK_ID = 1;

/*INSERT DA INFORMAÇÃO*/

INSERT INTO TB_USUARIO (DS_LOGIN, DS_SENHA, NR_TELEFONE, DS_CEP, DS_UF, DS_CIDADE, DS_BAIRRO, DS_LOGRADOURO, NR_LOGRADOURO, DS_NOME, DS_EMAIL, NR_CPFCNPJ, FK_NIVEL)
VALUES ('exemplo_login', 'exemplo_senha', '123456789', '12345-678', 'SP', 'São Paulo', 'Centro', 'Avenida Exemplo', '123', 'Exemplo Nome', 'exemplo@example.com', '12345678900', 1);

/*UPDATE DA INFORMAÇÃO*/

UPDATE TB_USUARIO
SET DS_LOGIN = 'novo_login',
    DS_SENHA = 'nova_senha',
    NR_TELEFONE = '987654321',
    DS_CEP = '54321-098',
    DS_UF = 'RJ',
    DS_CIDADE = 'Rio de Janeiro',
    DS_BAIRRO = 'Copacabana',
    DS_LOGRADOURO = 'Avenida Nova',
    NR_LOGRADOURO = '456',
    DS_NOME = 'Novo Nome',
    DS_EMAIL = 'novo_email@example.com',
    NR_CPFCNPJ = '98765432100',
    FK_NIVEL = 2
WHERE PK_ID = 1;

/*DELETE DA INFORMAÇÃO*/

DELETE FROM TB_USUARIO
WHERE PK_ID = 1;

/*------------------------------------*/


/*CRUDE TELA DE FORMAS DE PAGAMENTO*/

/*PESQUISA DE TODOS OS ITENS*/

SELECT
	PK_ID,
    FK_USUARIO,
    DS_CARTAO,
    DS_PIX,
    BOLETO
FROM TB_FORMAPAGAMENTO;    

/*SELECT ITEM SELCIONADO*/

SELECT
	PK_ID,
    FK_USUARIO,
    DS_CARTAO,
    DS_PIX,
    BOLETO
FROM TB_FORMAPAGAMENTO;
WHERE PK_ID = 1;

/*INSERT DA INFORMAÇÃO*/

INSERT INTO TB_FORMAPAGAMENTO (FK_USUARIO, DS_CARTAO, DS_PIX, BOLETO)
VALUES (1, '1234567812345678', 'exemplo.pix@example.com', 'https://exemplo.com/boleto');


/*UPDATE DA INFORMAÇÃO*/

UPDATE TB_FORMAPAGAMENTO
SET DS_CARTAO = '9876543210987654',
    DS_PIX = 'novo.exemplo.pix@example.com',
    BOLETO = 'https://novo-exemplo.com/boleto'
WHERE FK_USUARIO = 1;

/*DELETE DA INFORMAÇÃO*/
    
DELETE FROM TB_FORMAPAGAMENTO
WHERE FK_USUARIO = 1;

/*------------------------------*/


/*RELATÓRIO PEDIDO POR FILTROS*/
/*TIPOS DE FILTROS: CATEGORIAS, DATA DE, DATA ATÉ, VALOR TOTAL, ID*/

/*RELATÓRIO ITENS PEDIDO POR FILTROS*/
/*TIPOS DE FILTROS: CATEGORIAS, DATA DE, DATA ATÉ, VALOR TOTAL, ID*/

-- CLIENTES MAIS GASTÕES
-- ORDERNAR POR QUEM COMPROU MAIS POR VALOR DO PEDIDO DE COMPRA